### ISSUE TITLE
Consider making core interfaces (ISolution, IInstance, ISolver) pydantic base classes.

### ISSUE THREAD

**Issue by lucawrabetz** [lucawrabetz/opti-face#21]

**Comment by Peter-Sanders** [comment]
#24 this is in scope here

**Comment by lucawrabetz** [comment]
Also, finish discussion for #25 first. We could potentially avoid pydantic altogether for this layer (interfaces for instance, solution, solver), based on the assumption that data validation happens in a layer (which we are roughly calling datamodel for now) where the feature class and db classes in PR #24 live, and that _separates_ the interface layer from the database, so that the interface does not require that type of validation. 

Let me know if you think this logic makes sense.

**Comment by lucawrabetz** [comment]
It seems clear to me that the layer discussion in my previous comment is the best way to go. In other words, we should:

- identify a clear set of components in the system that constitute the data validation layer, and consider making these objects pydantic objects
- no other objects (such as the core interfaces or the Feature class) will be pydantic objects to keep them lightweight
- all other objects (non validation layer objects) only receive data from the validation layer, so we can build them with clear predictable invariants without any validation

@Peter-Sanders can you second this?

**Comment by Peter-Sanders** [comment]
Yes  I think this makes sense
